### ISSUE TITLE
Use relative file paths

### ISSUE THREAD

**Issue by peterdesmet** [inbo/wmh-analysis#1]
- Make use of here() package
- Place wmh-analysis.Rproj file in root

Usage:

    data <- read_csv(here(“data”, “raw”, “occurrences.csv”))

**Comment by stijnvanhoey** [comment]
+ adapt paths to the new folder structure (separating `data`, `src` and `figures`)

**Comment by stijnvanhoey** [comment]
closing here, thanks @milotictanja
